### ISSUE TITLE
Sincronizar a seção Coding Practices

### ISSUE THREAD

**Issue by marcelsud** [PHPSP/php-the-right-way#10]

**Comment by pauloelr** [comment]
A seção "Exceções" deve ser movida para o capitulo de "Erros e Exceções"
O @rogeriopradoj está trabalhando nessa reordenação das páginas.

A seção "Serialize" parece ter sido removida da versão em inglês, só não sei por qual motivo.

**Comment by rogeriopradoj** [comment]
@pauloelr está "on fire"!!! É isso aí!

**Comment by pauloelr** [comment]
Rsrs, to competindo com o @tonicospinelli que também mandou vários PR's

**Comment by tonicospinelli** [comment]
@pauloelr é um pair translating com um pouco de competitividade!! só quem ganha é a comunidade :)

**Comment by pauloelr** [comment]
É isso ai @tonicospinelli :smiley:

**Comment by rogeriopradoj** [comment]
Muito bem pessoal!

Go PHP community!

**Comment by pauloelr** [comment]
Corrigido no PR #51
Closing
