### ISSUE TITLE
Acompanhamento do Menu

### ISSUE THREAD

**Issue by pauloelr** [PHPSP/php-the-right-way#12]
Na versão em inglês a medida que vamos rolando a página pra baixo o menu lateral nos mostra em que seção estamos, adicionando um fundo amarelo ao item atual, acredito que essa modificação foi feita depois do Fork e não foi replicada na versão em português, seria interessante fazer essa implementação

**Comment by rogeriopradoj** [comment]
#49 do @tonicospinelli resolveu!
