### ISSUE TITLE
Repositório CC usado Ideologicamente

### ISSUE THREAD

**Issue by rdeprera** [PHPSP/php-the-right-way#157]
1. Neutralidade de gênero não faz parte da língua portuguesa oficial. Portanto, fazer uso de neutralidade de gênero tem, no mínimo, a intenção de fazer doutrinação ideológica das pessoas, ou, realizar provocação deliberada. Portanto, além de corrigir isso no repositório a @dianaarnos deve nos dizer qual das duas intenções ela teve
2. A maior parte da população não concorda com neutralidade de gênero
3. Neutralidade de gênero é usada como instrumento para chamarem outras pessoas, contrárias a seu uso, de homofóbicas, racistas, machistas e outros "istas". É um instrumento de ameaça mediante assédio

Não é necessário ser muito inteligente para adivinhar o posicionamento político da @dianaarnos. Agora, deixar que ela use este repositório para fazer política é um desserviço para com a comunidade.

Espero que esse absurdo seja resolvido rapidamente aqui, sem que seja necessário escalar a issue.

**Comment by casimiroarruda** [comment]
1. Neutralidade de gênero é um recurso da língua desde sempre. O que é novo e não está na língua são os pronomes inclusivos e os sufixos de gênero. Inclusão nada tem ligação a doutrinação ideológica. O fato de ter uma linguagem que contemple mais pessoas é justamente para que mais pessoas sintam-se reconhecidas nesse material. Caso sinta-se provocado, podemos conversar a respeito, desde que esteja aberto a ouvir e não traga nenhuma outra doutrinação ideológica como argumento irrefutável.
2. Qual pesquisa corrobora essa opinião?
3. Como dito no item 1, a abordagem linguística usada é justamente para impactar mais pessoas, incluso quem não concorda com ela

Fico a disposição para DIALOGAR a respeito

Atenciosamente

Anderson

**Comment by nawarian** [comment]
Fico muito feliz de ver a resposta respeitosa do @casimiroarruda mas acho importante ser enfático quanto a alguns pontos cruciais desta conversa.

Eu não vou entrar no mérito da linguagem neutra, acho que não cabe aqui a discussão. Mas sim o seguinte:

## Licença

O projeto [PHP the Right Way](https://phptherightway.com/) é distribuído sob licença [CC-BY NC SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/), que indica explicitamente que todEs são livres para distribuir e adaptar o conteúdo.

Adaptar a linguagem para um formato mais inclusivo não apenas concorda com os termos da licença como reforça o nosso [código de conduta](https://phpsp.org.br/codigo-de-conduta/).

TODAS pessoas são bem-vindas à comunidade PHPSP, e a gramática não vai deve ser usada como ferramenta de segregação.

## Atenção para o código de conduta

O [Código de Conduta estipulado pela comunidade PHPSP](https://phpsp.org.br/codigo-de-conduta/) explicita o seguinte:

> [...] Não será tolerado, sob nenhuma circunstância, o constrangimento de participantes em eventos e canais organizados pela comunidade.

Note que o comentário de @rdeprera:

- Não é construtivo ou propositivo;
- Demanda que alguém que contribuiu com o projeto justifique sua contribuição;

Além disso, o pull request #156 que já foi revisado, aprovado e integrado, também contém um comentário de @rdeprera novamente indicando indignação com o conteúdo da contribuição da colega Diana Arnos.

**Voltemos ao código de conduta da comunidade PHPSP:**

> Entendemos como assédio e constrangimento:
> - comentários que reforçam estruturas sociais de dominação, sejam relacionados a gênero, identidade e expressão de gênero, orientação sexual, deficiência, aparência física, raça, idade, origem ou religião;
> ...
> - **perseguição**

Sendo este um **canal organizado pela comunidade** a atitude do colega @rdeprera é desprezível e não deve ser tolerada!

## Conclusão

> Os participantes que violarem estas regras podem ser repreendidos, suspensos ou até mesmo expulsos e impedidos de participarem dos canais oficiais da comunidade e seus eventos.

A comunidade deve agir imediatamente sobre o caso e **proibir** o usuário @rdeprera de participar tanto de nossos canais de comunicação quanto contribuir com o Github do PHPSP.

**Comment by Morkhusz** [comment]
> 1. Neutralidade de gênero não faz parte da língua portuguesa oficial. Portanto, fazer uso de neutralidade de gênero tem, no mínimo, a intenção de fazer doutrinação ideológica das pessoas, ou, realizar provocação deliberada. Portanto, além de corrigir isso no repositório a @dianaarnos deve nos dizer qual das duas intenções ela teve

Sobre a parte da lingua portuguesa nem vale a pena eu tentar argumentar algo pq já está bem claro que o autor deste comentário não sabe nem o que está falando e o @casimiroarruda já deu um excelente ponto.
A questão do sujeito insinuar que estamos com a intenção de fazer doutrinação ideológica já é absurda por si só, quanto mais cobrar um posicionamento de alguém que está contribuindo EFETIVAMENTE para a comunidade. O PR citado foi **revisado** e **aprovado** pela comunidade, a @dianaarnos não DEVE dizer a ninguém qual a intenção dela com este PR pq a intenção aqui é clara: contribuir com um material de qualidade, traduzido para o pt-br e com linguagem INCLUSIVA.

> 2. A maior parte da população não concorda com neutralidade de gênero

Reforço o ponto do Casimiro, onde está essa pesquisa concluída e de fonte confiável? E outro ponto: a maior parte da população não contribui para a tradução do PHPTRW, é uma minoria que contribui, se preocupando a tornar o conteúdo acessível e inclusivo

> 3. Neutralidade de gênero é usada como instrumento para chamarem outras pessoas, contrárias a seu uso, de homofóbicas, racistas, machistas e outros "istas". É um instrumento de ameaça mediante assédio

Bicho, isso aqui é o item mais absurdo que li nos últimos anos nesta comunidade, vc deveria ler o código de conduta antes de falar asneira dessa forma. Não é legal vir num projeto público, para a comunidade, focado em trazer conteúdo relevante e inclusivo, dizendo que uma tradução CORRETA é um "instrumento de ameaça mediante assédio"

> Não é necessário ser muito inteligente para adivinhar o posicionamento político da @dianaarnos. Agora, deixar que ela use este repositório para fazer política é um desserviço para com a comunidade.
> Espero que esse absurdo seja resolvido rapidamente aqui, sem que seja necessário escalar a issue.

O único absurdo aqui é uma pessoa que nunca vi contribuindo para nada da comunidade **exigir** posicionamento de quem está contribuindo e ainda querer agilidade na resolução do problema que só existe na cabeça dele.

Concluindo aqui: sugiro que primeiramente o sujeito se ponha no teu lugar, leia o código de conduta e pense mais vezes (se é que pensou 1x) antes de insinuar e exigir coisas de um projeto para a comunidade.
Em segundo lugar apoio o banimento do elemento, proibindo a contribuição nos repos (que já deu pra ver que não será bem uma contribuição) e banindo dos meios de comunicação da comunidade.

**Comment by rdeprera** [comment]
>
> 1. Neutralidade de gênero é um recurso da língua desde sempre ...
>
Negativo. Usar *todes* é erro ortográfico, o correto é todas. O relativismo
"recurso de linguagem" é uma mágica que não pode ser usada ou qualquer erro
ortográfico deixa de ser um erro e passa a ser um "recurso de linguagem".
Use o "recurso de linguagem" em um vestibular e será corrigido em nota.
Quando isso deixar de ser uma fato, mudamos os professores.

> 2. Qual pesquisa corrobora essa opinião?
>
Amigo, é erro ortográfico. Não é a Google que redigi as regras ortográficas.

> 3. Como dito no item 1, a abordagem linguística usada é justamente para
> impactar mais pessoas, incluso quem não concorda com ela
>
Certamentamente. Impacta negativamente para quem concorda com a regra e
impacta positivamente para quem está transgredindo a regra ortográfica a
título de um posicionamento ideológico. A pergunta é:  vai continuar
fazendo política no repositório?

https://www.youtube.com/watch?v=hch2OYPpwGE



Em ter., 6 de set. de 2022 às 06:16, Anderson Casimiro <
***@***.***> escreveu:

**Comment by casimiroarruda** [comment]
Acho que alguém precisa ler, socializar e contribuir mais, ao invés de informar-se em grupos ou canais de ativismo político de gosto duvidoso.

Norma faz parte da comunicação, mas não a define. A língua portuguesa é riquíssima e permite, entre outras coisas, que novas formas sejam inseridas na comunicação. Como achas que a palavra "você" entrou na língua?

Um adendo: os corretores estão se atualizando para linguagem inclusiva.

**Comment by nawarian** [comment]
Fica decidido por votação da organização PHPSP que o usuário @rdeprera deverá ser impedido de colaborar e participar dos canais da comunidade PHPSP por motivo de **intimidação intencional** e **perseguição**.
