### ISSUE TITLE
Capitulo "Gerenciamento de Dependencias"

### ISSUE THREAD

**Issue by pauloelr** [PHPSP/php-the-right-way#16]
As seções "Updating your dependencies" e "Checking your dependencies for security issues" sobre Composer são novas e não foram ainda incluídas nas versão em português

Praticamente toda a seção sobre PEAR é nova e não foi incluída na versãoe m português.

**Comment by marcelsud** [comment]
Obrigado @tonicospinelli

**Comment by tonicospinelli** [comment]
@marcelsud tamo junto!
