### ISSUE TITLE
Capitulo "Segurança"

### ISSUE THREAD

**Issue by pauloelr** [PHPSP/php-the-right-way#19]
Praticamente toda a seção sobre "Hash de Senhas" foi alterada.
A Seção sobre "Relatório de Erros" tem alguns problemas de formatação dos blocos de código que estão sendo exibidos como se fossem textos normais
Nessa mesma seção a citação do php.net também está mal formatada
E no final do capitulo está faltando um dos links

**Comment by marcelsud** [comment]
Obrigado @tonicospinelli

**Comment by tonicospinelli** [comment]
@marcelsud tamo junto!
