### ISSUE TITLE
Capitulo "Recursos"

### ISSUE THREAD

**Issue by pauloelr** [PHPSP/php-the-right-way#23]
As listas de Recursos estão desatualizadas
Seção de "Componentes" Faltando

**Comment by pauloelr** [comment]
@tonicospinelli quase que eu peguei a mesma issue que você, rsrsr
Publica por favor um comentário antes de começar a trabalhar na issue pra gente não acabar fazendo a mesma coisa?

**Comment by tonicospinelli** [comment]
firmeza!! eu vi que mudou muita coisa, inclusive que foi adicionado um novo capítulo

**Comment by pauloelr** [comment]
Macro capitulo não que eu tenha visto.
Mas varias sub-seções foram adicionadas sim

**Comment by pauloelr** [comment]
Fechando pois o PR já foi submetido
