### ISSUE TITLE
Branch Master Outdated

### ISSUE THREAD

**Issue by pauloelr** [PHPSP/php-the-right-way#57]
Pessoas,

Alguém sabe por que além da branch gh-pages existe uma branch master?
Eu dei uma olhada nela e parece que ela é somente uma branch antiga de quando o projeto ainda não era desenvolvido usando Jekyll, é isso mesmo?
Se sim não seria melhor excluí-la para não confundir?

**Comment by klaussilveira** [comment]
Páginas de usuário ficam no master, enquanto páginas de projeto ficam no gh-pages.

https://help.github.com/articles/creating-pages-with-the-automatic-generator

**Comment by pauloelr** [comment]
Mas nesse caso não tem nenhuma página de usuário válida, ou tem?
Mesmo por que teria que ser em um repositório com nome do tipo username/username.github.io, ou não?

Não entendo muito dessa convenção de nomes e branchs do GitHub, mas o que parece é que nesse repositório especificamente a branch master não está sendo usada para nada. Ou eu estou totalmente errado?

**Comment by klaussilveira** [comment]
Sim, não está sendo usada. Mas também não fez sentido removê-la, uma vez que nosso repositório é um fork do The Right Way original. Caso eles façam algo com a master, precisamos portar.

**Comment by pauloelr** [comment]
Entendi,

Acho que caso eles fizessem alguma coisa com a master só teríamos que criar a branch de novo.
Só jeito que está acho que acaba confundindo as pessoas que querem contribuir, já que a maioria dos projetos usa a branch master como a principal e as pessoas já estão acostumadas com isso.
Mas entendo o ponto de manter a compatibilidade.

**Comment by pauloelr** [comment]
Só complementando.

Eu abri o mesmo issue no repositório da versão original, assim se eles não forem mais usar a Branch Master eles podem excluir lá e nos só replicamos aqui. 

Vou fechar a issue daqui por enquanto, se houver alguma mudança por lá eu volto a abrir essa issue para que façamos a mudança. :smiley:

**Comment by pauloelr** [comment]
Oi,

Estou reabrindo essa aqui pois, como eu tinha dito, havia sugerido essa mesma modificação no projeto original, e hoje essa sugestão foi aceita, então acho que agora já podemos excluir essa branch master. Podemos?

Se tiver tudo ok eu mesmo posso fazer daqui, só achei melhor confirmar com vocês antes.

**Comment by rogeriopradoj** [comment]
Paulo, pode apagar o branch master.

Para mantermos a referência, issue no repositório original: https://github.com/codeguy/php-the-right-way/issues/342

**Comment by pauloelr** [comment]
Done.

Eu fiz um backup local dela antes só por garantia.
Closing

**Comment by rogeriopradoj** [comment]
Valeu!
