### ISSUE TITLE
The Basics - Sintaxe Heredoc (Ajuste)

### ISSUE THREAD

**Issue by wellingtonslima** [PHPSP/php-the-right-way#64]
Acredito que tenha um erro de sintaxe na sessão "Sintaxe Heredoc" está assim:

$str = <<<EOD
Exemplo de string
pulando multiplas linhas
usando a sintaxe heredoc.
$a são interpretadas.
EOD; 

quando deveria ser:

$str = <<<EOT
Exemplo de string
pulando multiplas linhas
usando a sintaxe heredoc.
$a são interpretadas.
EOT;

**Comment by pauloelr** [comment]
Não,

Na verdade essa é a diferença entra nowdoc e heredoc, no Heredoc as variáveis são sim interpretadas, já no Nowdoc elas não são interpretadas, então o texto atual está correto.

Mais detalhes aqui:
http://www.php.net/manual/pt_BR/language.types.string.php#language.types.string.syntax.heredoc
http://www.php.net/manual/pt_BR/language.types.string.php#language.types.string.syntax.nowdoc

**Comment by rogeriopradoj** [comment]
@wellingtonsl, a única mudança que você mostrou foi entre EOD e EOT, é isso?

**Comment by larruda** [comment]
@wellingtonsl https://github.com/wellingtonsl, o identificador é apenas
uma string qualquer, não precisa ser igual à documentação. EOD, EOT, HTML,
BLABLA... funcionam :)

só pode conter caracteres alfanuméricos e sublinhados, e precisa começar
com um caracter não numérico ou sublinhado

> @wellingtonsl https://github.com/wellingtonsl, a única mudança que você
> mostrou foi entre EOD e EOT, é isso?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PHPSP/php-the-right-way/issues/64#issuecomment-37258686
> .

## 

_Lucas Arruda_

**Comment by pauloelr** [comment]
Nossa,

Agora que eu vi que tinha uma diferença ali no identificador, preciso treinar melhor minha atenção, srrsrs

**Comment by rogeriopradoj** [comment]
@wellingtonsl, vamos fechar a issue, ok? Se achar interessante continuar a discussão, é só chamar.

Até mais!

**Comment by wellingtonslima** [comment]
Desculpe a demora em responder, estava com problemas.

Mas minha dúvida era realmente em relação ao identificador, pois lembrava
dos exemplos do php.net, e fiquei com isso na cabeça.
Desculpa por ter aberto uma issue incorreta.

Mas a iniciativa de vocês é muito boa, pois acredito que a comunidade php
está com carência de boas práticas de desenvolvimento.

Espero contribuir de uma forma mais construtiva em uma próxima vez,
obrigado.

On Tue, Mar 11, 2014 at 12:28 AM, Rogerio Prado de Jesus <
notifications@github.com> wrote:

> Closed #64 https://github.com/PHPSP/php-the-right-way/issues/64.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/PHPSP/php-the-right-way/issues/64
> .

## 

Att.
Wellington Santana.

**Comment by rogeriopradoj** [comment]
Tranquilo, @wellingtonsl. Por favor, não fique com receio de perguntar não, só assim vamos aumentando nosso conhecimento.

Pode ter certeza que foi uma issue construtiva, ok?

Se quiser contribuir conosco, temos vários caminhos:
- acompanhando a versão em inglês, http://www.phptherightway.com/, e dizendo se tem algum conteúdo novo lá (abrir issue)
- revisar esta versão para ver se tem erros, igual você fez (abrir issue)
- mandar pull requests já com os acertos, revisões, novos textos etc. que você conseguir fazer
- apenas mostrar seu apoio!! (dar "star" aqui no GitHub, compartilhar via Twitter, Facebook, Google+ etc.)

Até mais!
