### ISSUE TITLE
Sincronizar a seção Language Highlights

### ISSUE THREAD

**Issue by marcelsud** [PHPSP/php-the-right-way#9]

**Comment by pauloelr** [comment]
Especialmente as seções sobre Programação Funcional e Meta Programação
Também os últimos parágrafos da seção sobre xDebug
PS: Estou fazendo uma revisão do que precisa ser feito pra ajudar o pessoal que quiser contribuir.
    Por isso estou comentando as issues com mais informações relativas a elas

**Comment by pauloelr** [comment]
Como o @tonicospinelli já alterou a seção sobre xDebug vou corrigir as seções de Programação Funcional e Meta Programação assim já terminamos essa issue também.

**Comment by marcelsud** [comment]
Obrigado @pauloelr.
